print (f'|{28*'-'}|')
print ('| Calculadora')
print (f'|{28*'-'}|')
print ('| 1 - soma')
print ('| 2 - subtração')
print ('| 3 - multiplicação')
print ('| 4 - divisão')
print (f'|{28*'-'}|')
escolha = input ('escolha uma das opções: ')
n1 = input ('escolha')
