carro = input ('digite o nome do carro: ')
valor = input ('digite o valor do carro: ')
consumo = input ('digite o consumo KM/L: ')
print(f'{"-"*33}')
print('| carro: ', carro)
print('| valor:', valor)
print('| consumo:', consumo)